name: checkout code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          java-package: jdk

      - name: Build with Maven
        run: mvn clean install

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: target/my-app.jar 


  builds:
    runs-on: ubuntu-latest
      steps:
      - name: Build Docker image
        run: |
          docker build -t git-action-demo .

      - name: Push Docker image (optional)
        run: |
          docker tag my-app-image dhananjaytupe/git-action-demo:latest
          docker push dhananjaytupe/git-action-demo:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
