name: checkout code

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          java-package: jdk

      - name: Build with Maven
        run: mvn clean install

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: target/my-app.jar 

  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download JAR Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-app  # Ensure the artifact name matches the one used in the previous job

      - name: Build Docker image
        run: |
          docker build -t git-action-demo .

      - name: Push Docker image
        run: |
          docker tag git-action-demo dhananjaytupe/git-action-demo:latest
          docker push dhananjaytupe/git-action-demo:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
